### ISSUE TITLE
Gradient Penalty Implementations 

### ISSUE THREAD

**Issue by PaTricksStar** [Aixile/chainer-gan-experiments#1]
Can you tell me where I can find the Gradient Penalty Implementations code ?

**Comment by Aixile** [comment]
https://github.com/Aixile/chainer-gan-experiments/blob/master/common/models/ops.py
https://github.com/Aixile/chainer-gan-experiments/blob/master/common/models/backwards.py
https://github.com/Aixile/chainer-gan-experiments/blob/master/dragan/updater.py

Ref differentiable_backward function

**Comment by PaTricksStar** [comment]
so I have to call the functions in backwards.py layer by layer ?

**Comment by Aixile** [comment]
Yes, I did the backward procedure manually. But you can wait for Chainer 3.0 (Release next month) which will officially support gradient penalty.

**Comment by PaTricksStar** [comment]
oh, thanks!
